[package]
name = "i8080"
version = "0.1.0"
edition = "2021"

[lib]
name = "rs_8080"
path = "src/lib.rs"

[[bin]]
name = "i8080"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1.13", features = ["derive"] }
env_logger = "0.8.4"
log = "0.4.0"
rand = "0.8.4"
rustyline = "9.1.2"
